apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: university
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your_dockerhub_user/therapyconnect-backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: therapyconnect-secrets
          command: ["/bin/sh", "-c"]
          args:
            - >
              python manage.py migrate &&
              gunicorn backend.wsgi:application --bind 0.0.0.0:8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: university
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: backend
