# Generated by Django 4.2.24 on 2025-09-03 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(help_text='Format: p_xxxxxx (e.g., p_abc123)', max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Patient ID must be in format p_xxxxxx where x is lowercase alphanumeric', regex='^p_[a-z0-9]{6}$')])),
                ('password', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long'), django.core.validators.MaxLengthValidator(64, message='Password cannot exceed 64 characters')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ssn', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='SSN must be in format XXX-XX-XXXX', regex='^\\d{3}-\\d{2}-\\d{4}$')])),
                ('phone_no', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be valid and contain 9-15 digits', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('added_note', models.TextField(blank=True, max_length=500, null=True)),
                ('allergies_and_medication', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='patient_profiles/')),
                ('about_note', models.TextField(blank=True, max_length=250, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sessions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
