# Generated by Django 5.2.6 on 2025-09-03 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.CharField(help_text='Format: t_xxxxxx (e.g., t_abc123)', max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Therapist ID must be in format t_xxxxxx where x is lowercase alphanumeric', regex='^t_[a-z0-9]{6}$')])),
                ('password', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long'), django.core.validators.MaxLengthValidator(64, message='Password cannot exceed 64 characters')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ssn', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='SSN must be in format XXX-XX-XXXX', regex='^\\d{3}-\\d{2}-\\d{4}$')])),
                ('phone_no', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be valid and contain 9-15 digits', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('house_addr', models.TextField(blank=True, null=True)),
                ('work_addr', models.TextField(blank=True, null=True)),
                ('verified_certificates', models.JSONField(blank=True, default=list)),
                ('years_active', models.PositiveIntegerField(default=0)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('education', models.JSONField(default=list)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='therapist_profiles/')),
                ('area_of_expertise', models.JSONField(blank=True, default=list)),
                ('about_note', models.TextField(blank=True, max_length=300, null=True)),
                ('availability', models.JSONField(blank=True, default=list)),
                ('average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.RegexValidator(message='Score must be between 0.00 and 5.00', regex='^[0-5]\\.\\d{2}$')])),
                ('no_payment', models.BooleanField(default=False)),
                ('no_payment_patients', models.JSONField(blank=True, default=list)),
                ('receive_emergency_messages', models.BooleanField(default=False)),
                ('can_send_emergency_messages', models.JSONField(blank=True, default=list)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Therapist',
                'verbose_name_plural': 'Therapists',
                'db_table': 'therapists',
                'ordering': ['-created_at'],
            },
        ),
    ]
