# Generated by Django 4.2.24 on 2025-09-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0003_chat_message_notebook_page_payment_review_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.CharField(help_text='Format: AVAIL_{therapist_id}_{YYYYMMDD}_{slot}', max_length=50, primary_key=True, serialize=False)),
                ('therapist_id', models.CharField(max_length=8)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('8-9', '8:00-9:00'), ('9-10', '9:00-10:00'), ('10-11', '10:00-11:00'), ('11-12', '11:00-12:00'), ('12-13', '12:00-13:00'), ('13-14', '13:00-14:00'), ('14-15', '14:00-15:00'), ('15-16', '15:00-16:00'), ('16-17', '16:00-17:00'), ('17-18', '17:00-18:00'), ('18-19', '18:00-19:00'), ('19-20', '19:00-20:00'), ('20-21', '20:00-21:00'), ('21-22', '21:00-22:00')], max_length=10)),
                ('session_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availabilities',
                'db_table': 'availabilities',
                'ordering': ['date', 'time_slot'],
            },
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sessions',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='availability',
        ),
        migrations.AlterField(
            model_name='therapist',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
