# Generated by Django 5.2.6 on 2025-09-04 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0004_availability_remove_patient_sessions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.CharField(help_text='Format: ROOM_{therapist_id}_{patient_id}', max_length=20, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('therapy', 'Therapy Session'), ('consultation', 'Consultation'), ('emergency', 'Emergency'), ('general', 'General Chat')], default='general', max_length=20)),
                ('therapist_can_send', models.BooleanField(default=True)),
                ('patient_can_send', models.BooleanField(default=True)),
                ('therapist_can_see_history', models.BooleanField(default=True)),
                ('patient_can_see_history', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'db_table': 'chat_rooms',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message_sender_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='patient_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='patient_unread_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('blocked', 'Blocked'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='chat',
            name='therapist_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='therapist_unread_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('system', 'System'), ('appointment', 'Appointment'), ('prescription', 'Prescription')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='read_by',
            field=models.CharField(blank=True, help_text='ID of user who read the message', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='read_status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='therapy.message'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('therapist_id', 'patient_id')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat_id', 'timestamp'], name='messages_chat_id_f83a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_id', 'timestamp'], name='messages_sender__557813_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['read_status', 'timestamp'], name='messages_read_st_51e0d5_idx'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='therapy.chat'),
        ),
    ]
