# Generated by Django 4.2.24 on 2025-09-08 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0007_alter_patient_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='phone_no',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format 09XXXXXXXXX (11 digits)', regex='^09\\d{9}$')]),
        ),
    ]
